<#
.SYNOPSIS
    Generates a human-readable mapping of Wolf ISM7 parameter PTIDs to their
    German names, grouped by device template (DTID).

.DESCRIPTION
    Your config/ism7-parameters-<device>.json file references parameters only by
    numeric PTID. This script joins the embedded resource files:
      - device.xml     (DeviceTemplate DTID -> list of ParameterReference PTIDs)
      - parameter.xml  (Parameter PTID -> Name, Unit, App-visibility, writable...)
    and emits:
      - parameter-map.csv  : every DTID/PTID/Name (filterable in Excel)
      - parameter-map.md   : same, grouped per device template as Markdown tables

    Names are the German display names (the add-on runs in DEU mode, where the
    template Name is already the German label).

.PARAMETER Dtid
    Optional list of device template IDs to restrict the output to (the numbers
    that appear as "DeviceTemplateId" in your parameter.json). If omitted, all
    device templates are emitted.

.EXAMPLE
    ./generate-parameter-map.ps1 -Dtid 190000,220000,240000,340000,350000
#>
[CmdletBinding()]
param(
    [string]$ResourceDir = (Join-Path $PSScriptRoot '..\ism7mqtt\src\ism7mqtt\Resources'),
    [string]$OutDir = $PSScriptRoot,
    [int[]]$Dtid
)

$ErrorActionPreference = 'Stop'

$paramFile  = Join-Path $ResourceDir 'parameter.xml'
$deviceFile = Join-Path $ResourceDir 'device.xml'

Write-Host "Loading $paramFile ..."
[xml]$pdoc = Get-Content -LiteralPath $paramFile -Raw
Write-Host "Loading $deviceFile ..."
[xml]$ddoc = Get-Content -LiteralPath $deviceFile -Raw

# PTID -> parameter info
$params = @{}
foreach ($node in $pdoc.ParameterTemplateConfig.ParameterList.ChildNodes) {
    if ($node.NodeType -ne [System.Xml.XmlNodeType]::Element) { continue }
    $ptid = [int]$node.GetAttribute('PTID')
    $nameEl  = $node['Name']
    $unitEl  = $node['UnitName']
    $ctrlEl  = $node['ControlType']
    $appEl   = $node['App']
    $roEl    = $node['ReadOnlyConditionId']
    $params[$ptid] = [pscustomobject]@{
        PTID     = $ptid
        Name     = if ($nameEl) { $nameEl.InnerText } else { '' }
        Unit     = if ($unitEl) { $unitEl.InnerText } else { '' }
        Control  = if ($ctrlEl) { $ctrlEl.InnerText } else { '' }
        InApp    = if ($appEl)  { $appEl.InnerText -eq 'true' } else { $false }
        Writable = if ($roEl)   { $roEl.InnerText -eq 'False' } else { $false }
        Type     = $node.LocalName
    }
}
Write-Host "Parsed $($params.Count) parameter templates."

# DTID -> device + referenced PTIDs
$rows = New-Object System.Collections.Generic.List[object]
foreach ($dt in $ddoc.DeviceTemplateConfig.DeviceTemplates.DeviceTemplate) {
    $thisDtid = [int]$dt.GetAttribute('DTID')
    if ($Dtid -and ($thisDtid -notin $Dtid)) { continue }
    $deviceName = $dt.GetAttribute('Name')
    $refList = $dt['ParameterReferenceList']
    if (-not $refList) { continue }
    foreach ($pr in $refList.ChildNodes) {
        if ($pr.NodeType -ne [System.Xml.XmlNodeType]::Element) { continue }
        $ptid = [int]$pr.GetAttribute('PTID')
        $expertAttr = $pr.GetAttribute('ExpertOnly')
        $expertOnly = -not ($expertAttr -eq 'false')   # default true when absent
        $p = $params[$ptid]
        $rows.Add([pscustomobject]@{
            DTID       = $thisDtid
            Device     = $deviceName
            PTID       = $ptid
            Name       = if ($p) { $p.Name } else { '(unknown PTID)' }
            Unit       = if ($p) { $p.Unit } else { '' }
            Control    = if ($p) { $p.Control } else { '' }
            Writable   = if ($p) { $p.Writable } else { '' }
            InApp      = if ($p) { $p.InApp } else { '' }
            ExpertOnly = $expertOnly
        })
    }
}
Write-Host "Produced $($rows.Count) device/parameter rows."

# CSV
$csvPath = Join-Path $OutDir 'parameter-map.csv'
$rows | Sort-Object DTID, PTID | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Encoding UTF8
Write-Host "Wrote $csvPath"

# Markdown grouped by device template
$mdPath = Join-Path $OutDir 'parameter-map.md'
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Wolf ISM7 parameter map (PTID -> name)')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Generated by `tools/generate-parameter-map.ps1`. Names are the German display labels.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('- **InApp = false** -> parameter is normally hidden in the Wolf app (e.g. PV/SmartGrid items).')
[void]$sb.AppendLine('- **Writable = true** -> can be set; false -> read-only sensor.')
[void]$sb.AppendLine('')
foreach ($grp in ($rows | Group-Object DTID | Sort-Object { [int]$_.Name })) {
    $first = $grp.Group[0]
    [void]$sb.AppendLine("## DTID $($grp.Name) - $($first.Device)  ($($grp.Count) parameters)")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('| PTID | Name | Unit | Writable | InApp |')
    [void]$sb.AppendLine('| --- | --- | --- | --- | --- |')
    foreach ($r in ($grp.Group | Sort-Object PTID)) {
        $name = $r.Name -replace '\|', '\|'
        [void]$sb.AppendLine("| $($r.PTID) | $name | $($r.Unit) | $($r.Writable) | $($r.InApp) |")
    }
    [void]$sb.AppendLine('')
}
Set-Content -LiteralPath $mdPath -Value $sb.ToString() -Encoding UTF8
Write-Host "Wrote $mdPath"
